In [82]:
import pandas as pd
import numpy as np

# macroregion Eurasia only
Languages = pd.read_csv('Languages.csv')
Languages.family_pk = Languages.family_pk.fillna(-1).apply(int)

Languages

,bookkeeping,category,child_dialect_count,child_family_count,child_language_count,description,family_pk,father_pk,hid,id,jsondata,latitude,level,longitude,macroareas,markup_description,name,newick,pk
0,True,Bookkeeping,0,0,0,NaN,342,342.0,aay,aari1240,"{""iso_retirement"": {""code"": ""aay"", ""name"": ""Aa...",NaN,language,NaN,Eurasia,NaN,Aariya,'Aariya [aari1240][aay]-l-':1,1427
1,False,Spoken L1 Language,3,0,0,NaN,300,1091.0,abq,abaz1241,"{""iso_retirement"": null, ""ethnologue_comment"":...",44.250000,language,42.000000,Eurasia,NaN,Abaza,"('Ashkaraua [ashk1247]':1,'Bezshagh [bezs1238]...",3005
2,False,Spoken L1 Language,3,0,0,NaN,300,1091.0,abk,abkh1244,"{""iso_retirement"": null, ""ethnologue_comment"":...",43.056218,language,41.159115,Eurasia,NaN,Abkhaz,"('Abzhui [abzh1238]':1,'Bzyb [bzyb1238]':1,'Sa...",3006
3,False,Spoken L1 Language,3,0,0,NaN,351,12637.0,acn,acha1249,"{""iso_retirement"": null, ""ethnologue_comment"":...",24.347900,language,97.743800,Eurasia,NaN,Longchuan Achang,"('Longchuan [long1373]':1,'Maingtha [main1270]...",15234
4,False,Spoken L1 Language,0,0,0,NaN,351,15230.0,yif,ache1244,"{""iso_retirement"": null, ""ethnologue_comment"":...",24.152000,language,102.446000,Eurasia,NaN,Ache,'Ache [ache1244][yif]-l-':1,17748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1972,False,Spoken L1 Language,6,0,0,NaN,273,19776.0,gbz,zoro1242,"{""iso_retirement"": null, ""ethnologue_comment"":...",31.816100,language,54.446900,Eurasia,NaN,Zoroastrian Yazdi,"('Gabri {Iranian} [gabr1257]':1,('Judeo-Kerman...",21502
1973,False,Spoken L1 Language,0,0,0,NaN,351,7156.0,czt,zotu1235,"{""iso_retirement"": null, ""ethnologue_comment"":...",22.529800,language,93.290000,Eurasia,NaN,Zotung Chin,'Zotung Chin [zotu1235][czt]-l-':1,9834
1974,False,Spoken L1 Language,0,0,0,NaN,351,9824.0,zom,zouu1235,"{""iso_retirement"": null, ""ethnologue_comment"":...",24.064900,language,93.925300,Eurasia,NaN,Zou,'Zou [zouu1235][zom]-l-':1,12766
1975,False,Spoken L1 Language,0,0,0,NaN,77,7881.0,zzj,zuoj1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",22.400000,language,106.900000,Eurasia,NaN,Zuojiang Zhuang,'Zuojiang Zhuang [zuoj1238][zzj]-l-':1,10554
1976,False,Spoken L1 Language,2,0,0,NaN,351,9833.0,zyp,zyph1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",22.524000,language,93.264000,Eurasia,NaN,Zyphe,"('Lower Zyphe [lowe1400]':1,'Upper Zyphe [uppe...",12783

In [83]:
# https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers#Ethnologue_(2019,_22nd_edition)
TopLanguages = pd.read_csv('TopLanguages.tsv', sep='\t').set_index('Rank')
TopLanguages

                  Language  Millions  Percent         Family     Subfamily
Rank
1         Mandarin Chinese     918.0  11.922%   Sino-Tibetan       Sinitic
2                  Spanish     480.0   5.994%  Indo-European       Romance
3                  English     379.0   4.922%  Indo-European      Germanic
4                    Hindi     341.0   4.429%  Indo-European    Indo-Aryan
5                  Bengali     300.0   4.000%  Indo-European    Indo-Aryan
...                    ...       ...      ...            ...           ...
87                   Czech      10.7   0.139%  Indo-European  Balto-Slavic
88    Taʽizzi-Adeni Arabic      10.5   0.136%    Afroasiatic       Semitic
89                  Uyghur      10.4   0.135%         Turkic        Karluk
90             Eastern Min      10.3   0.134%   Sino-Tibetan       Sinitic
91                 Sylheti      10.3   0.134%  Indo-European    Indo-Aryan

[91 rows x 5 columns]

In [88]:
TopLanguages[~TopLanguages.Language.isin(set(Languages.name))]

,Language,Millions,Percent,Family,Subfamily
Rank,,,,,
9,Western Punjabi,92.7,1.204%,Indo-European,Indo-Aryan
21,Javanese,68.3,0.887%,Austronesian,Malayo-Polynesian
23,Egyptian Arabic,64.6,0.839%,Afroasiatic,Semitic
25,Iranian Persian,52.8,0.686%,Indo-European,Iranian
27,Southern Min,50.1,0.651%,Sino-Tibetan,Sinitic
28,Hakka,48.2,0.626%,Sino-Tibetan,Sinitic
29,Jin Chinese,46.9,0.609%,Sino-Tibetan,Sinitic
30,Hausa,43.9,0.570%,Afroasiatic,Chadic
32,Indonesian,43.4,0.564%,Austronesian,Malayo-Polynesian
34,Yoruba,37.8,0.491%,Niger–Congo,Volta–Niger
40,Eastern Punjabi,32.6,0.423%,Indo-European,Indo-Aryan
41,Sunda,32.4,0.421%,Austronesian,Malayo-Polynesian
42,Sudanese Arabic,31.9,0.414%,Afroasiatic,Semitic
43,Algerian Arabic,29.4,0.382%,Afroasiatic,Semitic
44,Moroccan Arabic,27.5,0.357%,Afroasiatic,Semitic
46,Igbo,27.0,0.351%,Niger–Congo,Volta–Niger
51,Tagalog,23.6,0.306%,Austronesian,Malayo-Polynesian
53,Saʽidi Arabic,22.4,0.291%,Afroasiatic,Semitic
55,Amharic,21.9,0.284%,Afroasiatic,Semitic
60,Khmer,16.6,0.216%,Austroasiatic,Khmer
62,Somali,16.2,0.210%,Afroasiatic,Cushitic
63,Malaysian (Malaysian Malay),16.1,0.209%,Austronesian,Malayo-Polynesian
64,Cebuano,15.9,0.206%,Austronesian,Malayo-Polynesian
66,Mesopotamian Arabic,15.7,0.204%,Afroasiatic,Semitic
68,Sinhalese,15.3,0.199%,Indo-European,Indo-Aryan
70,Hejazi Arabic,14.5,0.188%,Afroasiatic,Semitic
71,Nigerian Fulfulde,14.5,0.188%,Niger–Congo,Senegambian
74,Greek,13.1,0.170%,Indo-European,Hellenic
77,Deccan,12.8,0.166%,Indo-European,Indo-Aryan
79,Kinyarwanda,12.1,0.157%,Niger–Congo,Bantu
80,Zulu,12.1,0.157%,Niger–Congo,Bantu
82,Tunisian Arabic,11.6,0.151%,Afroasiatic,Semitic
83,Sanaani Spoken Arabic,11.4,0.148%,Afroasiatic,Semitic
84,Northern Min,11.0,0.143%,Sino-Tibetan,Sinitic
86,Rundi,10.8,0.140%,Niger–Congo,Bantu
88,Taʽizzi-Adeni Arabic,10.5,0.136%,Afroasiatic,Semitic
89,Uyghur,10.4,0.135%,Turkic,Karluk
90,Eastern Min,10.3,0.134%,Sino-Tibetan,Sinitic

In [92]:
Languages[Languages.name.str.contains('ghur')].newick.iloc[0]

"(('Ili [ilii1241]':1,'Kashgar-Atush [kash1278]':1,'Qomul [qomu1235]':1,('Kucha [kuch1247]':1,'Moghal [mogh1248]':1,'Tarim [tari1268]':1)'Tarim-Moghal-Kucha [tari1267]':1,'Turfan [turf1238]':1,'Urumqi [urum1248]':1)'Central Uyghur [cent1994]':1,'Khotan [khot1252]':1,'Lopnor [lopn1238]':1)'Uighur [uigh1240][uig]-l-':1"

In [43]:
Families = pd.read_csv('Families.csv')
Families.describe()

,child_dialect_count,child_family_count,child_language_count,description,family_pk,father_pk,latitude,longitude,markup_description,pk
count,427.000000,427.000000,427.000000,0.0,0.0,0.0,184.000000,184.000000,0.0,427.000000
mean,29.967213,10.131148,19.557377,NaN,NaN,NaN,3.828375,9.462919,NaN,214.000000
std,194.146039,62.171893,104.800765,NaN,NaN,NaN,19.950016,101.661503,NaN,123.408536
min,0.000000,0.000000,0.000000,NaN,NaN,NaN,-55.274800,-124.379000,NaN,1.000000
25%,0.000000,0.000000,0.000000,NaN,NaN,NaN,-8.035970,-75.405275,NaN,107.500000
50%,1.000000,0.000000,2.000000,NaN,NaN,NaN,-3.117920,-45.522651,NaN,214.000000
75%,6.500000,2.000000,6.000000,NaN,NaN,NaN,14.017605,133.920000,NaN,320.500000
max,2501.000000,889.000000,1403.000000,NaN,NaN,NaN,48.789200,159.814000,NaN,427.000000

In [80]:
LangFamJoin = Languages[(~Languages.bookkeeping)&(Languages.family_pk>0)][['family_pk', 
                                      'name', 'level']].set_index('family_pk').join(Families[Families.pk>0][[
    'name', 'pk', 'level']].set_index('pk').rename(columns=lambda x: 'family_' +x)).drop('level', axis=1)

LangFamJoin.family_name.value_counts()

Indo-European          509
Sino-Tibetan           497
Austroasiatic          157
Tai-Kadai               95
Sign Language           90
Dravidian               79
Afro-Asiatic            67
Uralic                  48
Turkic                  44
Hmong-Mien              39
Nakh-Daghestanian       34
Unclassifiable          27
Austronesian            26
Pidgin                  19
Mongolic-Khitan         17
Artificial Language     15
Japonic                 14
Tungusic                13
Great Andamanese        10
Speech Register          7
Chukotko-Kamchatkan      7
Mixed Language           7
Unattested               6
Yeniseian                5
Kartvelian               5
Abkhaz-Adyge             5
Yukaghir                 4
Eskimo-Aleut             4
Ainu                     3
Koreanic                 2
Hurro-Urartian           2
Nivkh                    2
Jarawa-Onge              2
Name: family_name, dtype: int64

In [81]:
LangFamJoin[LangFamJoin.family_name == 'Koreanic']

       name family_name family_level
127  Jejueo    Koreanic       family
127  Korean    Koreanic       family

In [11]:
Languages[Languages.name.str.startswith('R')]

,bookkeeping,category,child_dialect_count,child_family_count,child_language_count,description,family_pk,father_pk,hid,id,jsondata,latitude,level,longitude,macroareas,markup_description,name,newick,pk
122,False,Spoken L1 Language,7,0,0,NaN,220.0,6479.0,bgx,balk1254,"{""iso_retirement"": null, ""ethnologue_comment"":...",41.170545,language,24.445670,Eurasia,NaN,Rumelian Turkish,"('Danubian [danu1248]':1,'Gajol [gajo1239]':1,...",9129
1425,False,Spoken L1 Language,2,0,0,NaN,351.0,4898.0,rah,rabh1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",25.824800,language,91.168900,Eurasia,NaN,Rabha,"('Maitaria [mait1251]':1,'Rangdania [rang1268]...",7197
1426,False,Spoken L1 Language,6,0,0,NaN,94.0,13697.0,rad,rade1240,"{""iso_retirement"": null, ""ethnologue_comment"":...",12.979000,language,108.410000,Eurasia,NaN,Rade,"('Adham [adha1237]':1,'Blo [bloo1242]':1,'Kodr...",16123
1427,False,Unclassifiable,0,0,0,NaN,394.0,394.0,xrr,raet1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",NaN,language,NaN,Eurasia,NaN,Raetic,'Raetic [raet1238][xrr]-l-':1,1778
1428,False,Spoken L1 Language,0,0,0,NaN,273.0,19727.0,rjs,rajb1243,"{""iso_retirement"": null, ""ethnologue_comment"":...",26.521945,language,88.038582,Eurasia,NaN,Rajbanshi,'Rajbanshi [rajb1243][rjs]-l-':1,21412
1429,False,Spoken L1 Language,0,0,0,NaN,351.0,1586.0,rji,raji1240,"{""iso_retirement"": null, ""ethnologue_comment"":...",28.615100,language,81.577000,Eurasia,NaN,Raji,'Raji [raji1240][rji]-l-':1,3197
1430,False,Spoken L1 Language,0,0,0,NaN,273.0,14973.0,gra,rajp1235,"{""iso_retirement"": null, ""ethnologue_comment"":...",24.545100,language,73.247200,Eurasia,NaN,Rajput Garasia,'Rajput Garasia [rajp1235][gra]-l-':1,17466
1431,False,Spoken L1 Language,0,0,0,NaN,351.0,12646.0,rki,rakh1245,"{""iso_retirement"": null, ""ethnologue_comment"":...",20.527429,language,93.145906,Eurasia,NaN,Rakhine,'Rakhine [rakh1245][rki]-l-':1,15249
1432,False,Spoken L1 Language,0,0,0,NaN,351.0,9823.0,ral,ralt1242,"{""iso_retirement"": null, ""ethnologue_comment"":...",25.020100,language,94.738100,Eurasia,NaN,Ralte,'Ralte [ralt1242][ral]-l-':1,12762
1433,False,Spoken L1 Language,0,0,0,NaN,273.0,9433.0,thr,rana1246,"{""iso_retirement"": null, ""ethnologue_comment"":...",28.648300,language,80.441900,Eurasia,NaN,Rana Tharu,'Rana Tharu [rana1246][thr]-l-':1,12414
1435,False,Spoken L1 Language,0,0,0,NaN,351.0,7106.0,rgk,rang1266,"{""iso_retirement"": null, ""ethnologue_comment"":...",29.227800,language,80.084500,Eurasia,NaN,Rangkas,'Rangkas [rang1266][rgk]-l-':1,9754
1437,True,Bookkeeping,0,0,0,NaN,342.0,342.0,NaN,rany1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",NaN,language,NaN,Eurasia,NaN,Ranya,'Ranya [rany1238]-l-':1,1198
1438,False,Spoken L1 Language,0,0,0,NaN,273.0,14982.0,bgd,rath1242,"{""iso_retirement"": null, ""ethnologue_comment"":...",21.437500,language,74.995800,Eurasia,NaN,Rathwi Bareli,'Rathwi Bareli [rath1242][bgd]-l-':1,17492
1439,False,Spoken L1 Language,0,0,0,NaN,273.0,14985.0,rtw,rath1243,"{""iso_retirement"": null, ""ethnologue_comment"":...",22.309000,language,73.186000,Eurasia,NaN,Rathawi,'Rathawi [rath1243][rtw]-l-':1,17496
1440,False,Spoken L1 Language,0,0,0,NaN,351.0,3198.0,rau,raut1239,"{""iso_retirement"": null, ""ethnologue_comment"":...",28.951800,language,81.161700,Eurasia,NaN,Raute,'Raute [raut1239][rau]-l-':1,4916
1441,False,Spoken L1 Language,3,0,0,NaN,280.0,21554.0,yea,ravu1237,"{""iso_retirement"": null, ""ethnologue_comment"":...",12.323100,language,75.626500,Eurasia,NaN,Ravula,"('Adiya [adiy1237]':1,'Pani Yerava [pani1257]'...",23003
1442,False,Spoken L1 Language,0,0,0,NaN,351.0,3198.0,jnl,rawa1264,"{""iso_retirement"": null, ""ethnologue_comment"":...",30.074200,language,80.800500,Eurasia,NaN,Rawat,'Rawat [rawa1264][jnl]-l-':1,4917
1443,False,Spoken L1 Language,15,0,0,NaN,351.0,1577.0,raw,rawa1265,"{""iso_retirement"": null, ""ethnologue_comment"":...",27.102700,language,97.073800,Eurasia,NaN,Rawang,"('Agu [aguu1241]':1,'Hpungsi [hpun1238]':1,'Ht...",3176
1444,False,Spoken L1 Language,0,0,0,NaN,273.0,21431.0,rat,raza1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",36.267000,language,50.002000,Eurasia,NaN,Razajerdi,'Razajerdi [raza1238][rat]-l-':1,22864
1445,False,Spoken L1 Language,0,0,0,NaN,77.0,10533.0,gir,redg1235,"{""iso_retirement"": null, ""ethnologue_comment"":...",23.186800,language,104.993000,Eurasia,NaN,Red Gelao,'Red Gelao [redg1235][gir]-l-':1,13400
1446,False,Spoken L1 Language,0,0,0,NaN,273.0,12406.0,rei,reli1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",18.121300,language,82.499600,Eurasia,NaN,Reli,'Reli [reli1238][rei]-l-':1,15044
1447,False,Spoken L1 Language,3,0,0,NaN,333.0,6964.0,ren,reng1252,"{""iso_retirement"": null, ""ethnologue_comment"":...",14.456000,language,107.945900,Eurasia,NaN,Rengao,"('Bahnar-Rengao [bahn1261]':1,'Sedang-Rengao [...",9617
1448,False,Spoken L1 Language,0,0,0,NaN,351.0,7152.0,NOCODE_Rengmitca,reng1255,"{""iso_retirement"": null, ""ethnologue_comment"":...",21.710864,language,92.367939,Eurasia,NaN,Rengmitca,'Rengmitca [reng1255]-l-':1,9821
1449,False,Spoken L1 Language,0,0,0,NaN,333.0,7000.0,ril,rian1261,"{""iso_retirement"": null, ""ethnologue_comment"":...",24.052100,language,98.833300,Eurasia,NaN,Riang (Myanmar),'Riang {Myanmar} [rian1261][ril]-l-':1,9659
1450,False,Spoken L1 Language,0,0,0,NaN,351.0,9904.0,ria,rian1262,"{""iso_retirement"": null, ""ethnologue_comment"":...",23.680300,language,92.032100,Eurasia,NaN,Riang (India),'Riang {India} [rian1262][ria]-l-':1,12812
1451,True,Bookkeeping,0,0,0,NaN,342.0,342.0,rie,rien1238,"{""iso_retirement"": {""code"": ""rie"", ""name"": ""Ri...",19.508400,language,102.591000,Eurasia,NaN,Rien,'Rien [rien1238][rie]-l-':1,1398
1452,False,Spoken L1 Language,0,0,0,NaN,273.0,15047.0,rhg,rohi1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",20.833082,language,92.393968,Eurasia,NaN,Rohingya,'Rohingya [rohi1238][rhg]-l-':1,17573
1453,False,Spoken L1 Language,0,0,0,NaN,273.0,14812.0,rge,roma1240,"{""iso_retirement"": null, ""ethnologue_comment"":...",38.634700,language,23.216400,Eurasia,NaN,Romano-Greek,'Romano-Greek [roma1240][rge]-l-':1,17258
1454,False,Mixed Language,0,0,0,NaN,226.0,929.0,rsb,roma1241,"{""iso_retirement"": null, ""ethnologue_comment"":...",45.255200,language,20.376200,Eurasia,NaN,Romano-Serbian,'Romano-Serbian [roma1241][rsb]-l-':1,2631
1455,False,Sign Language,0,0,0,NaN,249.0,4529.0,rms,roma1324,"{""iso_retirement"": null, ""ethnologue_comment"":...",44.929200,language,26.292400,Eurasia,NaN,Romanian Sign Language,'Romanian Sign Language [roma1324][rms]-l-':1,6668
1456,False,Spoken L1 Language,8,0,0,NaN,273.0,22640.0,roh,roma1326,"{""iso_retirement"": null, ""ethnologue_comment"":...",46.553800,language,9.928120,Eurasia,NaN,Romansh,"('Lower Engadine [lowe1386]':1,'Rumantsch Gris...",23856
1457,False,Spoken L1 Language,9,0,0,NaN,273.0,19495.0,ron,roma1327,"{""iso_retirement"": null, ""ethnologue_comment"":...",46.391300,language,24.225600,Eurasia,NaN,Romanian,"('Banat Romanian [bana1280]':1,'Bayash-Rudar [...",21232
1458,False,Spoken L1 Language,3,0,0,NaN,273.0,23855.0,rgn,roma1328,"{""iso_retirement"": null, ""ethnologue_comment"":...",44.234900,language,11.718900,Eurasia,NaN,Romagnol,"('Northern Romagnolo [nort2607]':1,'Sammarines...",24645
1459,False,Spoken L1 Language,0,0,0,NaN,333.0,4761.0,rmx,roma1331,"{""iso_retirement"": null, ""ethnologue_comment"":...",14.340000,language,107.447000,Eurasia,NaN,Romam,'Romam [roma1331][rmx]-l-':1,6961
1460,False,Pidgin,0,0,0,NaN,292.0,1059.0,NOCODE_Romanian-Pidgin-Arabic,roma1333,"{""iso_retirement"": null, ""ethnologue_comment"":...",NaN,language,NaN,Eurasia,NaN,Romanian Pidgin Arabic,'Romanian Pidgin Arabic [roma1333]-l-':1,2950
1461,False,Spoken L1 Language,2,0,0,NaN,351.0,7105.0,rnp,rong1264,"{""iso_retirement"": null, ""ethnologue_comment"":...",30.528000,language,79.567000,Eurasia,NaN,Rongpo,"('Marchha {India} [marc1245]':1,'Tolchha [tolc...",9752
1462,False,Spoken L1 Language,1,0,0,NaN,351.0,3170.0,nbu,rong1266,"{""iso_retirement"": null, ""ethnologue_comment"":...",25.098000,language,93.786900,Eurasia,NaN,Rongmei Naga,('Songbu [song1297]':1)'Rongmei Naga [rong1266...,4861
1463,False,Pidgin,0,0,0,NaN,292.0,1060.0,NOCODE_Roquetas-Pidgin-Spanish,roqu1234,"{""iso_retirement"": null, ""ethnologue_comment"":...",NaN,language,NaN,Eurasia,NaN,Roquetas Pidgin Spanish,'Roquetas Pidgin Spanish [roqu1234]-l-':1,2956
1464,False,Spoken L1 Language,2,0,0,NaN,333.0,6998.0,pce,ruch1235,"{""iso_retirement"": null, ""ethnologue_comment"":...",21.617600,language,98.091500,Eurasia,NaN,Ruching Palaung,"('Bulei [bule1241]':1,'Raojin [raoj1238]':1)'R...",9658
1465,False,Spoken L1 Language,9,0,0,NaN,273.0,17632.0,rdb,rudb1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",37.087800,language,49.880100,Eurasia,NaN,Rudbari,"('Dogowharani [dogo1301]':1,'Jamshidabadi [jam...",19767
1466,False,Spoken L1 Language,0,0,0,NaN,351.0,4898.0,ruh,ruga1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",25.506000,language,91.469000,Eurasia,NaN,Ruga,'Ruga [ruga1238][ruh]-l-':1,7199
1467,False,Spoken L1 Language,0,0,0,NaN,333.0,4778.0,rbb,ruma1248,"{""iso_retirement"": null, ""ethnologue_comment"":...",23.640400,language,97.317200,Eurasia,NaN,Rumai Palaung,'Rumai Palaung [ruma1248][rbb]-l-':1,6999
1468,False,Sign Language,3,0,0,NaN,249.0,2778.0,rsl,russ1255,"{""iso_retirement"": null, ""ethnologue_comment"":...",56.000000,language,44.000000,Eurasia,NaN,Russian-Tajik Sign Language,"('Kazakh-Russian Sign Language [kaza1251]':1,'...",4486
1469,False,Spoken L1 Language,13,0,0,NaN,273.0,6702.0,rus,russ1263,"{""iso_retirement"": null, ""ethnologue_comment"":...",59.000000,language,50.000000,Eurasia,NaN,Russian,"('Central Russian [cent2343]':1,'Ninilchik [ni...",9332
1470,False,Spoken L1 Language,9,0,0,NaN,2.0,5323.0,bxr,russ1264,"{""iso_retirement"": null, ""ethnologue_comment"":...",50.853300,language,105.564000,Eurasia,NaN,Russia Buriat,"('Alar [alar1239]':1,'Barguzin [barg1250]':1,'...",7669
1471,False,Pidgin,0,0,0,NaN,292.0,1036.0,NOCODE_Russenorsk,russ1267,"{""iso_retirement"": null, ""ethnologue_comment"":...",70.662000,language,23.681000,Eurasia,NaN,Russenorsk,'Russenorsk [russ1267]-l-':1,2917
1472,False,Spoken L1 Language,1,0,0,NaN,273.0,9335.0,rue,rusy1239,"{""iso_retirement"": null, ""ethnologue_comment"":...",48.717100,language,22.957900,Eurasia,NaN,Rusyn,('Lemko [lemk1239]':1)'Rusyn [rusy1239][rue]-l...,12247
1473,False,Spoken L1 Language,3,0,0,NaN,205.0,6394.0,rut,rutu1240,"{""iso_retirement"": null, ""ethnologue_comment"":...",41.618700,language,47.324400,Eurasia,NaN,Rutul,"('Borch [borc1243]':1,'Ixreko-Muxrek [ixre1238...",9024

In [12]:
Languages.columns

Index(['bookkeeping', 'category', 'child_dialect_count', 'child_family_count',
       'child_language_count', 'description', 'family_pk', 'father_pk', 'hid',
       'id', 'jsondata', 'latitude', 'level', 'longitude', 'macroareas',
       'markup_description', 'name', 'newick', 'pk'],
      dtype='object')

In [16]:
Languages.category.value_counts()

Spoken L1 Language     1702
Bookkeeping             104
Sign Language            90
Unclassifiable           27
Pidgin                   19
Artificial Language      15
Speech Register           7
Mixed Language            7
Unattested                6
Name: category, dtype: int64

In [17]:
Languages[Languages.category == 'Bookkeeping']

,bookkeeping,category,child_dialect_count,child_family_count,child_language_count,description,family_pk,father_pk,hid,id,jsondata,latitude,level,longitude,macroareas,markup_description,name,newick,pk
0,True,Bookkeeping,0,0,0,NaN,342.0,342.0,aay,aari1240,"{""iso_retirement"": {""code"": ""aay"", ""name"": ""Aa...",NaN,language,NaN,Eurasia,NaN,Aariya,'Aariya [aari1240][aay]-l-':1,1427
5,True,Bookkeeping,0,0,0,NaN,342.0,342.0,adp,adap1234,"{""iso_retirement"": {""code"": ""adp"", ""name"": ""Ad...",27.14100,language,90.33690,Eurasia,NaN,Adap,'Adap [adap1234][adp]-l-':1,1213
18,True,Bookkeeping,0,0,0,NaN,342.0,342.0,ahr,ahir1243,"{""iso_retirement"": null, ""ethnologue_comment"":...",21.55200,language,73.68500,Eurasia,NaN,Ahirani,'Ahirani [ahir1243][ahr]-l-':1,1282
88,True,Bookkeeping,0,0,0,NaN,342.0,342.0,xss,assa1266,"{""iso_retirement"": null, ""ethnologue_comment"":...",56.00000,language,94.00000,Eurasia,NaN,Assan,'Assan [assa1266][xss]-l-':1,1300
102,True,Bookkeeping,0,0,0,NaN,342.0,342.0,ayx,ayic1234,"{""iso_retirement"": {""code"": ""ayx"", ""name"": ""Ay...",27.12130,language,98.86840,Eurasia,NaN,Ayi (China),'Ayi {China} [ayic1234][ayx]-l-':1,1260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1925,True,Bookkeeping,0,0,0,NaN,342.0,342.0,ybd,yang1301,"{""iso_retirement"": {""code"": ""ybd"", ""name"": ""Ya...",18.52400,language,94.25430,Eurasia,NaN,Yangbye,'Yangbye [yang1301][ybd]-l-':1,1404
1934,True,Bookkeeping,0,0,0,NaN,342.0,342.0,yds,yidd1241,"{""iso_retirement"": {""code"": ""yds"", ""name"": ""Yi...",31.73420,language,34.78180,Eurasia,NaN,Yiddish Sign Language,'Yiddish Sign Language [yidd1241][yds]-l-':1,1367
1948,True,Bookkeeping,0,0,0,NaN,342.0,342.0,yos,yosa1234,"{""iso_retirement"": {""code"": ""yos"", ""name"": ""Yo...",25.43640,language,95.75660,Eurasia,NaN,Yos,'Yos [yosa1234][yos]-l-':1,1257
1955,True,Bookkeeping,0,0,0,NaN,342.0,342.0,yuu,yugh1240,"{""iso_retirement"": {""code"": ""yuu"", ""name"": ""Yu...",60.87784,language,89.74791,Eurasia,NaN,Yugh (Retired),'Yugh {Retired} [yugh1240][yuu]-l-':1,1544
1961,True,Bookkeeping,0,0,0,NaN,342.0,342.0,zrp,zarp1238,"{""iso_retirement"": null, ""ethnologue_comment"":...",45.56270,language,4.38771,Eurasia,NaN,Zarphatic,'Zarphatic [zarp1238][zrp]-l-':1,1484

In [18]:
Languages.describe()

,child_dialect_count,child_family_count,child_language_count,description,family_pk,father_pk,latitude,longitude,markup_description,pk
count,1977.00000,1977.0,1977.0,0.0,1965.000000,1965.000000,1925.000000,1925.000000,0.0,1977.000000
mean,2.37127,0.0,0.0,NaN,287.621883,9162.913995,30.272862,75.432760,NaN,11254.542236
std,5.97479,0.0,0.0,NaN,84.031526,6526.260995,13.132961,35.014729,NaN,6672.871804
min,0.00000,0.0,0.0,NaN,2.000000,2.000000,1.330690,-173.925000,NaN,51.000000
25%,0.00000,0.0,0.0,NaN,273.000000,3698.000000,22.295000,51.953800,NaN,5071.000000
50%,0.00000,0.0,0.0,NaN,280.000000,7881.000000,27.257200,85.561100,NaN,10545.000000
75%,3.00000,0.0,0.0,NaN,351.000000,13712.000000,37.176800,101.021000,NaN,16122.000000
max,125.00000,0.0,0.0,NaN,414.000000,25395.000000,73.135400,175.070000,NaN,25625.000000

In [28]:
TopLanguages.Language

Rank
1                       Mandarin Chinese
2                                Spanish
3                                English
4     Hindi (sanskritised Hindustani)[9]
5                                Bengali
                     ...
87                                 Czech
88                  Taʽizzi-Adeni Arabic
89                                Uyghur
90                           Eastern Min
91                               Sylheti
Name: Language, Length: 91, dtype: object

In [29]:
Languages.name

0                  Aariya
1                   Abaza
2                  Abkhaz
3        Longchuan Achang
4                    Ache
              ...
1972    Zoroastrian Yazdi
1973          Zotung Chin
1974                  Zou
1975      Zuojiang Zhuang
1976                Zyphe
Name: name, Length: 1977, dtype: object

In [37]:
Languages[Languages.name.str.contains('German')][['name', 'bookkeeping', 'pk']].sort_values('pk', ascending=False)

                                name  bookkeeping     pk
1187       German Northern Low Saxon        False  22822
1664                          German        False  22704
1186              Eastern Low German        False  21322
1060               Middle Low German        False  17298
1826      Central East Middle German        False  17287
1062              Middle High German        False  17284
1265  Old High German (ca. 750-1050)        False  14855
492             German Sign Language        False   4495
1684      Swiss-German Sign Language        False   4493
778         Kiautschou Pidgin German        False   2971
1910               WW2 Pidgin German        False   2970